version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: apache-airflow[google_auth]
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: pip
    versions:
    - "21.0"
    - 21.0.1
